//! Cross-language round-trip test: bytes produced by the TypeScript codec
//! (`@msgpack/msgpack`, via `packages/entity-sync-core/src/codec.ts`) must
//! decode correctly with the Rust codec. This is the real proof that both
//! sides agree on wire format — a same-language round-trip test can't
//! catch a bug where both encoder and decoder in one language share the
//! same wrong assumption.
//!
//! Fixtures are pre-generated hex files under `tests/fixtures/cross_lang/`
//! by `packages/entity-sync-core/scripts/generate-cross-lang-fixtures.ts`
//! (run via `pnpm --filter @prometheus-ags/entity-sync-core run
//! generate-fixtures`) and checked in, so this test has no Node.js runtime
//! dependency — it only reads the already-generated bytes.

use pes_core::{BucketId, Op, PgLsn};
use pes_protocol::{decode_client, decode_server, ClientMessage, ServerMessage};

fn read_fixture(name: &str) -> Vec<u8> {
    let path = format!(
        "{}/tests/fixtures/cross_lang/{name}.hex",
        env!("CARGO_MANIFEST_DIR")
    );
    let hex = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {path}: {e}. Run `pnpm --filter @prometheus-ags/entity-sync-core run generate-fixtures` first."));
    hex_decode(hex.trim())
}

fn hex_decode(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "hex string must have even length");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex byte"))
        .collect()
}

#[test]
fn typescript_encoded_snapshot_begin_decodes_correctly_in_rust() {
    let bytes = read_fixture("server_snapshot_begin");
    let decoded = decode_server(&bytes).expect("decode TypeScript-encoded SnapshotBegin");
    assert_eq!(
        decoded,
        ServerMessage::SnapshotBegin {
            bucket_id: BucketId("user_entities".to_string()),
            total_rows: 12345,
            protocol_version: 1,
        }
    );
}

#[test]
fn typescript_encoded_keepalive_decodes_correctly_in_rust() {
    let bytes = read_fixture("server_keepalive");
    let decoded = decode_server(&bytes).expect("decode TypeScript-encoded Keepalive");
    assert_eq!(
        decoded,
        ServerMessage::Keepalive {
            server_time_ms: 1_700_000_000_000,
        }
    );
}

#[test]
fn typescript_encoded_error_decodes_correctly_in_rust() {
    let bytes = read_fixture("server_error");
    let decoded = decode_server(&bytes).expect("decode TypeScript-encoded Error");
    assert_eq!(
        decoded,
        ServerMessage::Error {
            code: 4000,
            message: "unsupported protocol version".to_string(),
        }
    );
}

#[test]
fn typescript_encoded_subscribe_decodes_correctly_in_rust() {
    let bytes = read_fixture("client_subscribe");
    let decoded = decode_client(&bytes).expect("decode TypeScript-encoded Subscribe");
    assert_eq!(
        decoded,
        ClientMessage::Subscribe {
            buckets: vec!["user_entities".to_string(), "tenant_shared".to_string()],
            token: "eyJ.test.token".to_string(),
            resume_lsn: Some(PgLsn(42)),
            protocol_version: 1,
        }
    );
}

#[test]
fn typescript_encoded_ack_decodes_correctly_in_rust() {
    let bytes = read_fixture("client_ack");
    let decoded = decode_client(&bytes).expect("decode TypeScript-encoded Ack");
    assert_eq!(decoded, ClientMessage::Ack { lsn: PgLsn(99) });
}

#[test]
fn typescript_encoded_write_decodes_correctly_in_rust() {
    let bytes = read_fixture("client_write");
    let decoded = decode_client(&bytes).expect("decode TypeScript-encoded Write");
    assert_eq!(
        decoded,
        ClientMessage::Write {
            entity_type: "Todo".to_string(),
            entity_id: "t1".to_string(),
            op: Op::Upsert(serde_json::json!({"title": "cross-language test"})),
        }
    );
}

#[test]
fn typescript_encoded_ping_decodes_correctly_in_rust() {
    let bytes = read_fixture("client_ping");
    let decoded = decode_client(&bytes).expect("decode TypeScript-encoded Ping");
    assert_eq!(decoded, ClientMessage::Ping);
}
